name: flutter_amazon_clone
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  badges: ^3.0.3
  carousel_slider: ^4.2.1
  charts_flutter: ^0.12.0
  cloudinary_public: ^0.20.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  file_picker: ^5.2.7
  flutter:
    sdk: flutter
  flutter_charts: ^0.5.1
  flutter_rating_bar: ^4.0.1
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.8.0
  pay: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/applepay.json
    - assets/gpay.json
